"""Changes Detected!

Revision ID: 0053ae5e2e25
Revises: b8aedadbeda7
Create Date: 2023-11-19 19:43:19.709796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0053ae5e2e25'
down_revision: Union[str, None] = 'b8aedadbeda7'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
