"""Changes Detected!

Revision ID: 030e69bf9c34
Revises: e78127aee4bb
Create Date: 2023-11-14 18:29:33.399276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030e69bf9c34'
down_revision: Union[str, None] = 'e78127aee4bb'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
