"""Changes Detected!

Revision ID: 03aff0a5f56e
Revises: f5ed7f26e567
Create Date: 2023-11-20 03:39:27.558194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03aff0a5f56e'
down_revision: Union[str, None] = 'f5ed7f26e567'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
