"""Changes Detected!

Revision ID: 04cbdc3c0622
Revises: 7da0df8e31c4
Create Date: 2023-11-17 13:12:51.558055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04cbdc3c0622'
down_revision: Union[str, None] = '7da0df8e31c4'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
