"""Changes Detected!

Revision ID: 05f196c89b12
Revises: 48e8a3e05ffc
Create Date: 2023-11-15 03:42:52.239612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f196c89b12'
down_revision: Union[str, None] = '48e8a3e05ffc'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
