"""Changes Detected!

Revision ID: 096d95999c2d
Revises: e5207f2d9e25
Create Date: 2023-11-09 18:53:48.477545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096d95999c2d'
down_revision: Union[str, None] = 'e5207f2d9e25'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
