"""Changes Detected!

Revision ID: 0a12ea4bc9b2
Revises: 98a1d5d27c92
Create Date: 2023-11-19 18:40:51.013720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a12ea4bc9b2'
down_revision: Union[str, None] = '98a1d5d27c92'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
