"""Changes Detected!

Revision ID: 0dbcb3f4a9a0
Revises: db0c624494bf
Create Date: 2023-11-20 01:58:50.114895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbcb3f4a9a0'
down_revision: Union[str, None] = 'db0c624494bf'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
