"""Changes Detected!

Revision ID: 1228e25d6668
Revises: 90a81dc0ad20
Create Date: 2023-11-14 19:05:58.928528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1228e25d6668'
down_revision: Union[str, None] = '90a81dc0ad20'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
