"""Changes Detected!

Revision ID: 1331d5f00693
Revises: 49d9e1ee93ef
Create Date: 2023-11-14 19:02:34.916311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1331d5f00693'
down_revision: Union[str, None] = '49d9e1ee93ef'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
