"""Changes Detected!

Revision ID: 163e2e7e4297
Revises: 4246a13bb28e
Create Date: 2023-11-15 03:46:14.550942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163e2e7e4297'
down_revision: Union[str, None] = '4246a13bb28e'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
