"""Changes Detected!

Revision ID: 1677c40bcfca
Revises: 04cbdc3c0622
Create Date: 2023-11-17 13:13:28.750986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1677c40bcfca'
down_revision: Union[str, None] = '04cbdc3c0622'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
