"""Changes Detected!

Revision ID: 1a9b91d1a3bd
Revises: c43f0559d38c
Create Date: 2023-11-14 18:32:51.805532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9b91d1a3bd'
down_revision: Union[str, None] = 'c43f0559d38c'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
