"""Changes Detected!

Revision ID: 1b885e251087
Revises: 5bebbc11120b
Create Date: 2023-11-19 21:52:24.158620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b885e251087'
down_revision: Union[str, None] = '5bebbc11120b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_book_author', table_name='book_cart_association')
    op.drop_table('book_cart_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_cart_association',
    sa.Column('bookId', mysql.VARCHAR(length=715), nullable=False),
    sa.Column('cartId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookId'], ['Book.bookId'], name='book_cart_association_ibfk_1'),
    sa.ForeignKeyConstraint(['cartId'], ['Cart.cartId'], name='book_cart_association_ibfk_2'),
    sa.PrimaryKeyConstraint('bookId', 'cartId'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_book_author', 'book_cart_association', ['bookId', 'cartId'], unique=False)
    # ### end Alembic commands ###
