"""Changes Detected!

Revision ID: 1cdb20ecbd9a
Revises: 0a12ea4bc9b2
Create Date: 2023-11-19 18:40:56.214423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cdb20ecbd9a'
down_revision: Union[str, None] = '0a12ea4bc9b2'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
