"""Changes Detected!

Revision ID: 1f591e230f4b
Revises: 0053ae5e2e25
Create Date: 2023-11-19 19:43:24.762220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f591e230f4b'
down_revision: Union[str, None] = '0053ae5e2e25'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
