"""Changes Detected!

Revision ID: 241fec3f8cee
Revises: 178dd1fc7b0d
Create Date: 2023-11-17 16:40:27.455179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241fec3f8cee'
down_revision: Union[str, None] = '178dd1fc7b0d'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
