"""Changes Detected!

Revision ID: 25d56a34f8a9
Revises: c30ae38d3807
Create Date: 2023-11-19 19:39:02.896779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d56a34f8a9'
down_revision: Union[str, None] = 'c30ae38d3807'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
