"""Changes Detected!

Revision ID: 2daa5d996b93
Revises: c68e8fa0cf84
Create Date: 2023-11-15 02:05:12.543923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daa5d996b93'
down_revision: Union[str, None] = 'c68e8fa0cf84'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
