"""Changes Detected!

Revision ID: 3015fbf94cf1
Revises: f0b7279c13d2
Create Date: 2023-11-09 18:35:31.055131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3015fbf94cf1'
down_revision: Union[str, None] = 'f0b7279c13d2'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
