"""Changes Detected!

Revision ID: 302cd2c99f66
Revises: f53933ef7c70
Create Date: 2023-11-15 00:28:34.662535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302cd2c99f66'
down_revision: Union[str, None] = 'f53933ef7c70'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
