"""Changes Detected!

Revision ID: 31e5c9c8687f
Revises: b7e5bdffbe49
Create Date: 2023-11-20 03:01:04.690552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e5c9c8687f'
down_revision: Union[str, None] = 'b7e5bdffbe49'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
