"""Changes Detected!

Revision ID: 339cef7936f2
Revises: 1cdb20ecbd9a
Create Date: 2023-11-19 18:46:42.516217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339cef7936f2'
down_revision: Union[str, None] = '1cdb20ecbd9a'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
