"""Changes Detected!

Revision ID: 3a44fd1f89b6
Revises: fbed28dd3db4
Create Date: 2023-11-20 01:57:23.167604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a44fd1f89b6'
down_revision: Union[str, None] = 'fbed28dd3db4'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
