"""Changes Detected!

Revision ID: 3a88e8fb9ec9
Revises: 8110b82344cf
Create Date: 2023-11-14 23:12:53.982830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a88e8fb9ec9'
down_revision: Union[str, None] = '8110b82344cf'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
