"""Changes Detected!

Revision ID: 3e76ba63f83a
Revises: 2988e8a713ce
Create Date: 2023-11-14 18:41:07.801321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e76ba63f83a'
down_revision: Union[str, None] = '2988e8a713ce'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
