"""Changes Detected!

Revision ID: 3ffe06f9f6fa
Revises: ab97cdb15445
Create Date: 2023-11-17 15:58:31.642102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffe06f9f6fa'
down_revision: Union[str, None] = 'ab97cdb15445'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
