"""Changes Detected!

Revision ID: 41ef4cc9a61f
Revises: afb71d8e8eb9
Create Date: 2023-11-19 14:51:39.443841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ef4cc9a61f'
down_revision: Union[str, None] = 'afb71d8e8eb9'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
