"""Changes Detected!

Revision ID: 4287b33c9970
Revises: 768dcbe9ef22
Create Date: 2023-11-19 21:00:25.996888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4287b33c9970'
down_revision: Union[str, None] = '768dcbe9ef22'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
