"""Changes Detected!

Revision ID: 428bb84f8bfd
Revises: ba8406ecd35e
Create Date: 2023-11-19 18:52:28.317059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428bb84f8bfd'
down_revision: Union[str, None] = 'ba8406ecd35e'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
