"""Changes Detected!

Revision ID: 4558a1f6a7fd
Revises: 33b87a57a133
Create Date: 2023-11-19 18:57:16.783575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4558a1f6a7fd'
down_revision: Union[str, None] = '33b87a57a133'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
