"""Changes Detected!

Revision ID: 48e8a3e05ffc
Revises: a90c1d894f20
Create Date: 2023-11-15 03:37:14.798486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e8a3e05ffc'
down_revision: Union[str, None] = 'a90c1d894f20'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
