"""Changes Detected!

Revision ID: 49d9e1ee93ef
Revises: e607f6a19875
Create Date: 2023-11-14 19:01:17.746420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d9e1ee93ef'
down_revision: Union[str, None] = 'e607f6a19875'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
