"""Changes Detected!

Revision ID: 4eddf0075aff
Revises: 4e2ecd104f2a
Create Date: 2023-11-19 18:26:35.680609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eddf0075aff'
down_revision: Union[str, None] = '4e2ecd104f2a'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
