"""Changes Detected!

Revision ID: 5038f476afa9
Revises: 5d00aabd2b37
Create Date: 2023-11-20 03:04:12.088460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5038f476afa9'
down_revision: Union[str, None] = '5d00aabd2b37'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
