"""Changes Detected!

Revision ID: 50b9f5485fae
Revises: 4558a1f6a7fd
Create Date: 2023-11-19 18:59:49.637353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b9f5485fae'
down_revision: Union[str, None] = '4558a1f6a7fd'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
