"""Changes Detected!

Revision ID: 50f12bdc7fc7
Revises: 6accbf5a2c4a
Create Date: 2023-11-15 03:57:10.553826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f12bdc7fc7'
down_revision: Union[str, None] = '6accbf5a2c4a'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
