"""Changes Detected!

Revision ID: 53b4cfc9c146
Revises: 0dbcb3f4a9a0
Create Date: 2023-11-20 02:02:46.622930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b4cfc9c146'
down_revision: Union[str, None] = '0dbcb3f4a9a0'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
