"""Changes Detected!

Revision ID: 55548a3bfbc2
Revises: e3ae8f516d88
Create Date: 2023-11-20 02:48:50.743453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55548a3bfbc2'
down_revision: Union[str, None] = 'e3ae8f516d88'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('Cart', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cart', 'total_price')
    op.drop_column('Cart', 'quantity')
    # ### end Alembic commands ###
