"""Changes Detected!

Revision ID: 5623cd882d67
Revises: 5efe5fdd2bc9
Create Date: 2023-11-19 16:17:00.764583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5623cd882d67'
down_revision: Union[str, None] = '5efe5fdd2bc9'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
