"""Changes Detected!

Revision ID: 5667518b1022
Revises: 9e0ef0715ed6
Create Date: 2023-11-15 02:19:50.250524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5667518b1022'
down_revision: Union[str, None] = '9e0ef0715ed6'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
