"""Changes Detected!

Revision ID: 5a4c786fa2bb
Revises: b8ad45da6193
Create Date: 2023-11-14 17:16:25.513323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4c786fa2bb'
down_revision: Union[str, None] = 'b8ad45da6193'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
