"""Changes Detected!

Revision ID: 5ac597cf0b28
Revises: f1c1e8aec374
Create Date: 2023-11-08 02:27:57.926317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac597cf0b28'
down_revision: Union[str, None] = 'f1c1e8aec374'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
