"""Changes Detected!

Revision ID: 5bebbc11120b
Revises: 6e08a3b46256
Create Date: 2023-11-19 21:44:13.185079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5bebbc11120b'
down_revision: Union[str, None] = '6e08a3b46256'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Cart_ibfk_1', 'Cart', type_='foreignkey')
    op.drop_column('Cart', 'review_description')
    op.drop_column('Cart', 'rating')
    op.drop_column('Cart', 'bookId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('bookId', mysql.VARCHAR(length=715), nullable=False))
    op.add_column('Cart', sa.Column('rating', mysql.FLOAT(), nullable=False))
    op.add_column('Cart', sa.Column('review_description', mysql.VARCHAR(length=1000), nullable=False))
    op.create_foreign_key('Cart_ibfk_1', 'Cart', 'Book', ['bookId'], ['bookId'])
    # ### end Alembic commands ###
