"""Changes Detected!

Revision ID: 5d00aabd2b37
Revises: 31e5c9c8687f
Create Date: 2023-11-20 03:02:18.193562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d00aabd2b37'
down_revision: Union[str, None] = '31e5c9c8687f'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
