"""Changes Detected!

Revision ID: 5e07303adfa8
Revises: 3a88e8fb9ec9
Create Date: 2023-11-14 23:36:44.190662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e07303adfa8'
down_revision: Union[str, None] = '3a88e8fb9ec9'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
