"""Changes Detected!

Revision ID: 5edbe9ea0a2e
Revises: 5e07303adfa8
Create Date: 2023-11-14 23:48:11.522202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edbe9ea0a2e'
down_revision: Union[str, None] = '5e07303adfa8'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
