"""Changes Detected!

Revision ID: 5efe5fdd2bc9
Revises: 41ef4cc9a61f
Create Date: 2023-11-19 16:16:59.554632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efe5fdd2bc9'
down_revision: Union[str, None] = '41ef4cc9a61f'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
