"""Changes Detected!

Revision ID: 5f0be57abc83
Revises: 77e2e7d6f93b
Create Date: 2023-11-19 16:20:35.540295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0be57abc83'
down_revision: Union[str, None] = '77e2e7d6f93b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
