"""Changes Detected!

Revision ID: 5f1fbf6ad666
Revises: 4733559e4f6e
Create Date: 2023-11-15 02:24:27.873905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1fbf6ad666'
down_revision: Union[str, None] = '4733559e4f6e'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
