"""Changes Detected!

Revision ID: 6051eea44f3c
Revises: 7f584323eb7f
Create Date: 2023-11-17 16:21:58.280560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6051eea44f3c'
down_revision: Union[str, None] = '7f584323eb7f'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
