"""Changes Detected!

Revision ID: 60b6d3f48658
Revises: 53b4cfc9c146
Create Date: 2023-11-20 02:02:51.479577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b6d3f48658'
down_revision: Union[str, None] = '53b4cfc9c146'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
