"""Changes Detected!

Revision ID: 63706752602e
Revises: c2157731ebd4
Create Date: 2023-11-17 10:21:37.431076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63706752602e'
down_revision: Union[str, None] = 'c2157731ebd4'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bookId', 'Book', ['bookId'], unique=False)
    op.create_index('idx_userId', 'User', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_userId', table_name='User')
    op.drop_index('idx_bookId', table_name='Book')
    # ### end Alembic commands ###
