"""Changes Detected!

Revision ID: 67d8026c7b6b
Revises: b8b64a4d0978
Create Date: 2023-11-19 18:05:26.333228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d8026c7b6b'
down_revision: Union[str, None] = 'b8b64a4d0978'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
