"""Changes Detected!

Revision ID: 6accbf5a2c4a
Revises: 16e0e77fbab7
Create Date: 2023-11-15 03:57:07.457547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6accbf5a2c4a'
down_revision: Union[str, None] = '16e0e77fbab7'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
