"""Changes Detected!

Revision ID: 6cd4e0a5796b
Revises: e49ec94328ed
Create Date: 2023-11-09 18:39:20.801820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd4e0a5796b'
down_revision: Union[str, None] = 'e49ec94328ed'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
