"""Changes Detected!

Revision ID: 6d36e3220a7b
Revises: 3e76ba63f83a
Create Date: 2023-11-14 18:42:05.968122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d36e3220a7b'
down_revision: Union[str, None] = '3e76ba63f83a'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
