"""Changes Detected!

Revision ID: 6e08a3b46256
Revises: c5f5b3bd9c30
Create Date: 2023-11-19 21:44:10.976513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e08a3b46256'
down_revision: Union[str, None] = 'c5f5b3bd9c30'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
