"""Changes Detected!

Revision ID: 6e1505db94cd
Revises: e3bf9fbf1079
Create Date: 2023-11-19 19:41:31.349796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1505db94cd'
down_revision: Union[str, None] = 'e3bf9fbf1079'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
