"""Changes Detected!

Revision ID: 702c970ac2d7
Revises: ee683ca0026c
Create Date: 2023-11-17 13:39:37.644798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702c970ac2d7'
down_revision: Union[str, None] = 'ee683ca0026c'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
