"""Changes Detected!

Revision ID: 714a93d00ef7
Revises: 42dd02f2bfad
Create Date: 2023-11-08 02:35:22.445194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714a93d00ef7'
down_revision: Union[str, None] = '42dd02f2bfad'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
