"""Changes Detected!

Revision ID: 74b0e0758508
Revises: 5edbe9ea0a2e
Create Date: 2023-11-14 23:56:27.117853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b0e0758508'
down_revision: Union[str, None] = '5edbe9ea0a2e'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
