"""Changes Detected!

Revision ID: 7578c14539a9
Revises: c1c0e31330c3
Create Date: 2023-11-14 19:17:50.415152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7578c14539a9'
down_revision: Union[str, None] = 'c1c0e31330c3'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
