"""Changes Detected!

Revision ID: 7681a2095d68
Revises: aa1ec2c5e5e6
Create Date: 2023-11-20 04:36:23.391109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7681a2095d68'
down_revision: Union[str, None] = 'aa1ec2c5e5e6'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
