"""Changes Detected!

Revision ID: 768dcbe9ef22
Revises: 4053aebc9084
Create Date: 2023-11-19 21:00:23.945023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768dcbe9ef22'
down_revision: Union[str, None] = '4053aebc9084'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
