"""Changes Detected!

Revision ID: 77e2e7d6f93b
Revises: 7d7a09e61119
Create Date: 2023-11-19 16:19:40.825944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e2e7d6f93b'
down_revision: Union[str, None] = '7d7a09e61119'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
