"""Changes Detected!

Revision ID: 7884e03b46b3
Revises: 5f1fbf6ad666
Create Date: 2023-11-15 02:26:08.199974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7884e03b46b3'
down_revision: Union[str, None] = '5f1fbf6ad666'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
