"""Changes Detected!

Revision ID: 7cdc6919dfe2
Revises: 2be0ce8fdf99
Create Date: 2023-11-19 17:53:39.564258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cdc6919dfe2'
down_revision: Union[str, None] = '2be0ce8fdf99'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
