"""Changes Detected!

Revision ID: 7ded0ed26e6c
Revises: 2daa5d996b93
Create Date: 2023-11-15 02:05:15.553941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ded0ed26e6c'
down_revision: Union[str, None] = '2daa5d996b93'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
