"""Changes Detected!

Revision ID: 7f70f8d2b060
Revises: 7ded0ed26e6c
Create Date: 2023-11-15 02:10:41.548344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f70f8d2b060'
down_revision: Union[str, None] = '7ded0ed26e6c'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
