"""Changes Detected!

Revision ID: 8029b3091f14
Revises: f7b1bb640dad
Create Date: 2023-11-17 13:32:18.914226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8029b3091f14'
down_revision: Union[str, None] = 'f7b1bb640dad'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
