"""Changes Detected!

Revision ID: 84f5c0bc5ac3
Revises: 9703af6b6445
Create Date: 2023-11-08 02:16:36.862572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f5c0bc5ac3'
down_revision: Union[str, None] = '9703af6b6445'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
