"""Changes Detected!

Revision ID: 87b0e8118a86
Revises: b6b724d0b5e0
Create Date: 2023-11-19 19:01:22.540298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b0e8118a86'
down_revision: Union[str, None] = 'b6b724d0b5e0'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
