"""Changes Detected!

Revision ID: 8e3b74ee5fc8
Revises: cb75171229d2
Create Date: 2023-11-15 00:43:25.826779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3b74ee5fc8'
down_revision: Union[str, None] = 'cb75171229d2'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
