"""Changes Detected!

Revision ID: 90a81dc0ad20
Revises: b6ec75f740b3
Create Date: 2023-11-14 19:05:55.883299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a81dc0ad20'
down_revision: Union[str, None] = 'b6ec75f740b3'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
