"""Changes Detected!

Revision ID: 9703e01aaa72
Revises: ddd2d0f91c34
Create Date: 2023-11-17 17:26:29.790518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9703e01aaa72'
down_revision: Union[str, None] = 'ddd2d0f91c34'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
