"""Changes Detected!

Revision ID: 9703af6b6445
Revises: 9d8c4b14d34b
Create Date: 2023-11-08 02:12:42.673070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9703af6b6445'
down_revision: Union[str, None] = '9d8c4b14d34b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Book', 'bookId',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               nullable=False)
    op.alter_column('Book', 'title',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               nullable=False)
    op.alter_column('Book', 'series',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'author',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               nullable=False)
    op.alter_column('Book', 'rating',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Book', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'language',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'isbn',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'genres',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'characters',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'bookFormat',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'edition',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'pages',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Book', 'publisher',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'publishDate',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'firstPublishDate',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'awards',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'numRatings',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Book', 'ratingsByStars',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'likedPercent',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Book', 'setting',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'coverImg',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'bbeScore',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Book', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Book', 'price',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('Book', 'bbeScore',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('Book', 'coverImg',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'setting',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'likedPercent',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('Book', 'ratingsByStars',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'numRatings',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    op.alter_column('Book', 'awards',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'firstPublishDate',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'publishDate',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'publisher',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'pages',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    op.alter_column('Book', 'edition',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'bookFormat',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'characters',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'genres',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'isbn',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'language',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'description',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'rating',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('Book', 'author',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('Book', 'series',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'title',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('Book', 'bookId',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
