"""Changes Detected!

Revision ID: 97a53cfbc775
Revises: 0d5e0e8f29a5
Create Date: 2023-11-15 04:07:23.286089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a53cfbc775'
down_revision: Union[str, None] = '0d5e0e8f29a5'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
