"""Changes Detected!

Revision ID: 9833d1ec3141
Revises: 6d36e3220a7b
Create Date: 2023-11-14 18:45:04.236093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9833d1ec3141'
down_revision: Union[str, None] = '6d36e3220a7b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
