"""Changes Detected!

Revision ID: 98a1d5d27c92
Revises: cecb4d1bd2ad
Create Date: 2023-11-19 18:32:18.492029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a1d5d27c92'
down_revision: Union[str, None] = 'cecb4d1bd2ad'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
