"""Changes Detected!

Revision ID: 9d8c4b14d34b
Revises: 42a9e85a0c9b
Create Date: 2023-11-08 02:12:12.107024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8c4b14d34b'
down_revision: Union[str, None] = '42a9e85a0c9b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
