"""Changes Detected!

Revision ID: 9f128e3bcbc1
Revises: ce8e70778e43
Create Date: 2023-11-17 16:09:27.033050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f128e3bcbc1'
down_revision: Union[str, None] = 'ce8e70778e43'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
