"""Changes Detected!

Revision ID: 9fdf148de0c6
Revises: ce0a3797b01d
Create Date: 2023-11-14 17:13:24.377852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdf148de0c6'
down_revision: Union[str, None] = 'ce0a3797b01d'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
