"""Changes Detected!

Revision ID: a57aeee84b50
Revises: 1a9b91d1a3bd
Create Date: 2023-11-14 18:35:06.538871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57aeee84b50'
down_revision: Union[str, None] = '1a9b91d1a3bd'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
