"""Changes Detected!

Revision ID: a7422c55a8d9
Revises: 14a4307a48bb
Create Date: 2023-11-17 12:54:41.135147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7422c55a8d9'
down_revision: Union[str, None] = '14a4307a48bb'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Review', sa.Column('review_description', sa.String(length=1000), nullable=False))
    op.drop_column('Review', 'reiew_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Review', sa.Column('reiew_description', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_column('Review', 'review_description')
    # ### end Alembic commands ###
