"""Changes Detected!

Revision ID: aa1c9c2c12e9
Revises: 5f93b57da2ec
Create Date: 2023-11-09 19:01:05.795767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1c9c2c12e9'
down_revision: Union[str, None] = '5f93b57da2ec'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
