"""Changes Detected!

Revision ID: ab47ea0f076d
Revises: d0186aaaa4a7
Create Date: 2023-11-09 19:03:36.023027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab47ea0f076d'
down_revision: Union[str, None] = 'd0186aaaa4a7'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
