"""Changes Detected!

Revision ID: ab5b4f1bd96e
Revises: 7ab7a75f4cb5
Create Date: 2023-11-15 02:17:52.343602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5b4f1bd96e'
down_revision: Union[str, None] = '7ab7a75f4cb5'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
