"""Changes Detected!

Revision ID: afb71d8e8eb9
Revises: b2b5eb2f9f54
Create Date: 2023-11-19 14:51:38.145018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb71d8e8eb9'
down_revision: Union[str, None] = 'b2b5eb2f9f54'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
