"""Changes Detected!

Revision ID: b05aa65597da
Revises: ab5b4f1bd96e
Create Date: 2023-11-15 02:17:55.615687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05aa65597da'
down_revision: Union[str, None] = 'ab5b4f1bd96e'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
