"""Changes Detected!

Revision ID: b668555c814d
Revises: 84f5c0bc5ac3
Create Date: 2023-11-08 02:17:38.635082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b668555c814d'
down_revision: Union[str, None] = '84f5c0bc5ac3'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
