"""Changes Detected!

Revision ID: b6b724d0b5e0
Revises: 50b9f5485fae
Create Date: 2023-11-19 18:59:54.920547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b724d0b5e0'
down_revision: Union[str, None] = '50b9f5485fae'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
