"""Changes Detected!

Revision ID: b6e9f3fc9066
Revises: c9fb404069d2
Create Date: 2023-11-09 18:47:51.347179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e9f3fc9066'
down_revision: Union[str, None] = 'c9fb404069d2'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
