"""Changes Detected!

Revision ID: b8b64a4d0978
Revises: f9cc8e4c8be5
Create Date: 2023-11-19 18:03:56.915814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b64a4d0978'
down_revision: Union[str, None] = 'f9cc8e4c8be5'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
