"""Changes Detected!

Revision ID: ba8406ecd35e
Revises: ddb41dbff9e5
Create Date: 2023-11-19 18:51:31.853924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8406ecd35e'
down_revision: Union[str, None] = 'ddb41dbff9e5'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
