"""Changes Detected!

Revision ID: d0186aaaa4a7
Revises: 23bd87aa074c
Create Date: 2023-11-09 19:03:29.031656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0186aaaa4a7'
down_revision: Union[str, None] = '23bd87aa074c'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
