"""Changes Detected!

Revision ID: d1eb624a2695
Revises: 3e51c3bece75
Create Date: 2023-11-17 10:24:08.796301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1eb624a2695'
down_revision: Union[str, None] = '3e51c3bece75'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Review', 'bookId',
               existing_type=mysql.VARCHAR(length=715),
               nullable=False)
    op.alter_column('Review', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Review', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Review', 'bookId',
               existing_type=mysql.VARCHAR(length=715),
               nullable=True)
    # ### end Alembic commands ###
