"""Changes Detected!

Revision ID: d20c8a90e9bc
Revises: a7a7ed469299
Create Date: 2023-11-14 18:40:33.281562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20c8a90e9bc'
down_revision: Union[str, None] = 'a7a7ed469299'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
