"""Changes Detected!

Revision ID: ddb41dbff9e5
Revises: f7b49311cd9a
Create Date: 2023-11-19 18:51:01.127770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb41dbff9e5'
down_revision: Union[str, None] = 'f7b49311cd9a'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
