"""Changes Detected!

Revision ID: ddd2d0f91c34
Revises: 241fec3f8cee
Create Date: 2023-11-17 16:46:12.558129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd2d0f91c34'
down_revision: Union[str, None] = '241fec3f8cee'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
