"""Changes Detected!

Revision ID: de9f76e82ece
Revises: 5c5d519c225c
Create Date: 2023-11-20 01:54:21.729736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9f76e82ece'
down_revision: Union[str, None] = '5c5d519c225c'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('bookId', sa.String(length=715), nullable=False))
    op.create_foreign_key(None, 'Cart', 'Book', ['bookId'], ['bookId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cart', type_='foreignkey')
    op.drop_column('Cart', 'bookId')
    # ### end Alembic commands ###
