"""Changes Detected!

Revision ID: e19c75e37b30
Revises: fe91eb80f949
Create Date: 2023-11-09 16:47:07.684049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e19c75e37b30'
down_revision: Union[str, None] = 'fe91eb80f949'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Book', 'bookId',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               nullable=False)
    op.alter_column('Book', 'title',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               nullable=False)
    op.alter_column('Book', 'series',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'author',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               nullable=False)
    op.alter_column('Book', 'rating',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Book', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'language',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('Book', 'genres',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('Book', 'pages',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Book', 'publisher',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'publishDate',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'coverImg',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=715),
               existing_nullable=True)
    op.alter_column('Book', 'price',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False)
    op.drop_column('Book', 'Unnamed: 26')
    op.drop_column('Book', 'Unnamed: 41')
    op.drop_column('Book', 'Unnamed: 22')
    op.drop_column('Book', 'Unnamed: 40')
    op.drop_column('Book', 'Unnamed: 18')
    op.drop_column('Book', 'Unnamed: 35')
    op.drop_column('Book', 'Unnamed: 44')
    op.drop_column('Book', 'Unnamed: 55')
    op.drop_column('Book', 'Unnamed: 37')
    op.drop_column('Book', 'Unnamed: 13')
    op.drop_column('Book', 'Unnamed: 33')
    op.drop_column('Book', 'Unnamed: 54')
    op.drop_column('Book', 'Unnamed: 23')
    op.drop_column('Book', 'Unnamed: 30')
    op.drop_column('Book', 'Unnamed: 32')
    op.drop_column('Book', 'Unnamed: 39')
    op.drop_column('Book', 'Unnamed: 38')
    op.drop_column('Book', 'Unnamed: 15')
    op.drop_column('Book', 'Unnamed: 14')
    op.drop_column('Book', 'Unnamed: 29')
    op.drop_column('Book', 'Unnamed: 42')
    op.drop_column('Book', 'Unnamed: 52')
    op.drop_column('Book', 'Unnamed: 16')
    op.drop_column('Book', 'Unnamed: 45')
    op.drop_column('Book', 'Unnamed: 49')
    op.drop_column('Book', 'Unnamed: 24')
    op.drop_column('Book', 'Unnamed: 17')
    op.drop_column('Book', 'Unnamed: 20')
    op.drop_column('Book', 'Unnamed: 51')
    op.drop_column('Book', 'Unnamed: 27')
    op.drop_column('Book', 'Unnamed: 53')
    op.drop_column('Book', 'Unnamed: 21')
    op.drop_column('Book', 'Unnamed: 50')
    op.drop_column('Book', 'Unnamed: 36')
    op.drop_column('Book', 'Unnamed: 19')
    op.drop_column('Book', 'Unnamed: 48')
    op.drop_column('Book', 'Unnamed: 43')
    op.drop_column('Book', 'Unnamed: 47')
    op.drop_column('Book', 'Unnamed: 34')
    op.drop_column('Book', 'Unnamed: 25')
    op.drop_column('Book', 'Unnamed: 31')
    op.drop_column('Book', 'Unnamed: 28')
    op.drop_column('Book', 'Unnamed: 46')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Book', sa.Column('Unnamed: 46', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 28', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 31', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 25', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 34', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 47', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 43', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 48', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 19', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 36', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 50', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 21', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 53', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 27', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 51', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 20', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 17', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 24', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 49', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 45', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 16', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 52', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 42', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 29', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 14', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 15', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 38', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 39', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 32', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 30', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 23', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 54', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 33', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 13', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 37', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 55', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 44', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 35', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 18', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 40', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 22', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 41', mysql.TEXT(), nullable=True))
    op.add_column('Book', sa.Column('Unnamed: 26', mysql.TEXT(), nullable=True))
    op.alter_column('Book', 'price',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
    op.alter_column('Book', 'coverImg',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'publishDate',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'publisher',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'pages',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    op.alter_column('Book', 'genres',
               existing_type=sa.String(length=5000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'language',
               existing_type=sa.String(length=5000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'description',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'rating',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('Book', 'author',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('Book', 'series',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('Book', 'title',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               nullable=True)
    op.alter_column('Book', 'bookId',
               existing_type=sa.String(length=715),
               type_=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
