"""Changes Detected!

Revision ID: e29c82efb91c
Revises: f2e2a81a13ee
Create Date: 2023-11-14 19:25:02.788912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29c82efb91c'
down_revision: Union[str, None] = 'f2e2a81a13ee'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
