"""Changes Detected!

Revision ID: e35a5ad1fb6b
Revises: de9f76e82ece
Create Date: 2023-11-20 01:54:23.786747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35a5ad1fb6b'
down_revision: Union[str, None] = 'de9f76e82ece'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
