"""Changes Detected!

Revision ID: e607f6a19875
Revises: 5f8a05ba9dba
Create Date: 2023-11-14 19:00:49.629432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e607f6a19875'
down_revision: Union[str, None] = '5f8a05ba9dba'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
