"""Changes Detected!

Revision ID: e69036c720ea
Revises: 1a4497dc4f61
Create Date: 2023-11-15 01:12:15.206599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69036c720ea'
down_revision: Union[str, None] = '1a4497dc4f61'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_admin')
    # ### end Alembic commands ###
