"""Changes Detected!

Revision ID: e6b9dcf80b71
Revises: e02c4d9d2501
Create Date: 2023-11-15 04:24:34.399948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b9dcf80b71'
down_revision: Union[str, None] = 'e02c4d9d2501'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
