"""Changes Detected!

Revision ID: e6d9f26fefdd
Revises: 5f0be57abc83
Create Date: 2023-11-19 17:52:18.324182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d9f26fefdd'
down_revision: Union[str, None] = '5f0be57abc83'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
