"""Changes Detected!

Revision ID: eaaadf8e8ecd
Revises: 65d9bcbb8499
Create Date: 2023-11-14 17:55:31.789556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaaadf8e8ecd'
down_revision: Union[str, None] = '65d9bcbb8499'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
