"""Changes Detected!

Revision ID: f027b0264eb9
Revises: 0e41b700c8f3
Create Date: 2023-11-15 00:24:29.416064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f027b0264eb9'
down_revision: Union[str, None] = '0e41b700c8f3'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=55),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=55),
               existing_nullable=False)
    # ### end Alembic commands ###
