"""Changes Detected!

Revision ID: f49020e496ea
Revises: 8e3b74ee5fc8
Create Date: 2023-11-15 00:45:40.710347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49020e496ea'
down_revision: Union[str, None] = '8e3b74ee5fc8'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
