"""Changes Detected!

Revision ID: f7b49311cd9a
Revises: 1bf139f0d3ff
Create Date: 2023-11-19 18:50:23.528183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b49311cd9a'
down_revision: Union[str, None] = '1bf139f0d3ff'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
