"""Changes Detected!

Revision ID: f9cc8e4c8be5
Revises: dfdee319e885
Create Date: 2023-11-19 18:03:51.736228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cc8e4c8be5'
down_revision: Union[str, None] = 'dfdee319e885'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
