"""Changes Detected!

Revision ID: fb9d4ea35408
Revises: bf58ac5d4d35
Create Date: 2023-11-17 10:29:54.754806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9d4ea35408'
down_revision: Union[str, None] = 'bf58ac5d4d35'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
