"""Changes Detected!

Revision ID: fbed28dd3db4
Revises: e35a5ad1fb6b
Create Date: 2023-11-20 01:57:21.076442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbed28dd3db4'
down_revision: Union[str, None] = 'e35a5ad1fb6b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
