"""Changes Detected!

Revision ID: fc4c9df0d785
Revises: 7cdc6919dfe2
Create Date: 2023-11-19 17:54:21.793249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4c9df0d785'
down_revision: Union[str, None] = '7cdc6919dfe2'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
