"""Changes Detected!

Revision ID: fe75f5e50437
Revises: 6cd4e0a5796b
Create Date: 2023-11-09 18:41:57.297353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe75f5e50437'
down_revision: Union[str, None] = '6cd4e0a5796b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
